# Generated by Django 4.2 on 2023-04-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='country',
        ),
        migrations.AddField(
            model_name='airport',
            name='coordinates',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
