# Generated by Django 4.2 on 2023-04-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=111, null=True),
        ),
    ]
