# Generated by Django 4.2 on 2023-04-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_remove_staff_first_name_remove_staff_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='user_id',
            new_name='user',
        ),
    ]
